with-expecter: True # to assert the calls
dir: "../../internal/mocks" # called from cmd/main.go
mockname: "{{ .InterfaceName }}"
outpkg: "mocks"
filename: "mock_{{ .InterfaceName }}.go"
all: True
packages:
  github.com/kafkaphoenix/gosurf/internal/domain:
    config:
      recursive: False
