services:
  app:
    container_name: gosurf
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - app-network
    ports:
      - "8081:8081"
    env_file:
      - .env

networks:
  app-network:
