name: Lint and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Linter
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout=5m

      - name: Run unit tests
        run: go test -v ./... --tags=unit -coverpkg=./...

      - name: Run integration tests
        run: go test -v ./... --tags=integration -coverpkg=./...
